// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-j0mvNee0k3mojVGkpT2AxwnyWqe6rcY',
    appId: '1:1038187004820:web:1ecc2642eb0925cbe2c581',
    messagingSenderId: '1038187004820',
    projectId: 'compupay-5dca1',
    authDomain: 'compupay-5dca1.firebaseapp.com',
    storageBucket: 'compupay-5dca1.firebasestorage.app',
    measurementId: 'G-C1EY1SK028',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8JTail0sFIa5neJd-kHrknaP-f-FeKbY',
    appId: '1:1038187004820:android:d8f69c560355b078e2c581',
    messagingSenderId: '1038187004820',
    projectId: 'compupay-5dca1',
    storageBucket: 'compupay-5dca1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJx7SpwXodruxOFKaAO_jlz8nd8-XmVOo',
    appId: '1:1038187004820:ios:d135390e9f6644bae2c581',
    messagingSenderId: '1038187004820',
    projectId: 'compupay-5dca1',
    storageBucket: 'compupay-5dca1.firebasestorage.app',
    iosBundleId: 'com.example.compupayMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJx7SpwXodruxOFKaAO_jlz8nd8-XmVOo',
    appId: '1:1038187004820:ios:d135390e9f6644bae2c581',
    messagingSenderId: '1038187004820',
    projectId: 'compupay-5dca1',
    storageBucket: 'compupay-5dca1.firebasestorage.app',
    iosBundleId: 'com.example.compupayMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-j0mvNee0k3mojVGkpT2AxwnyWqe6rcY',
    appId: '1:1038187004820:web:5ec81528a0e6d8aee2c581',
    messagingSenderId: '1038187004820',
    projectId: 'compupay-5dca1',
    authDomain: 'compupay-5dca1.firebaseapp.com',
    storageBucket: 'compupay-5dca1.firebasestorage.app',
    measurementId: 'G-84F35Z1GX0',
  );
}
